voicegroup198::
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ spacer									@ 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 180
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ spacer									@ 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 165, 90, 216
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ spacer									@ 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 3, 15, 0
	voice_keysplit voicegroup007, KeySplitTable3
	voice_square_1_alt 60, 0, 0, 0, 0, 1, 4, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_pl_musicbox62, 255, 250, 2, 236
	voice_keysplit_all voicegroup199				 @ drums 10
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149
