	.align 2
voicegroup200:: @ 
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sc88pro_french_horn_60, 255, 247, 78, 196
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sc88pro_french_horn_60, 255, 200, 255, 171
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_sc88pro_french_horn_72, 255, 200, 255, 171
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_trumpet_60, 255, 255, 191, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_trumpet_72, 255, 255, 191, 32
	voice_directsound_no_resample 48, 64, DirectSoundWaveData_sc88pro_synth_bass, 2, 0, 255, 16
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_fretless_bass, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_slap_bass, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_unknown_snare, 255, 220, 0, 64
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_trinity_30303_mega_bass, 255, 0, 255, 0
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_slap_bass, 255, 0, 255, 171
	voice_directsound_no_resample 61, 58, DirectSoundWaveData_sd90_classical_oboe, 255, 220, 0, 16
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 0
	voice_directsound_no_resample 60, 70, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 226, 127, 0
	voice_directsound_no_resample 29, 30, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 32
	voice_directsound_no_resample 60, 80, DirectSoundWaveData_unknown_close_hihat, 255, 0, 227, 32
	voice_directsound_no_resample 34, 40, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 32
	voice_directsound_no_resample 60, 80, DirectSoundWaveData_sc88pro_glockenspiel, 255, 0, 235, 16
	voice_directsound_no_resample 41, 50, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 32
	voice_directsound_no_resample 60, 80, DirectSoundWaveData_unknown_open_hihat, 255, 241, 0, 0
	voice_directsound_no_resample 47, 100, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 32
	voice_directsound_no_resample 53, 107, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 32
	voice_directsound_no_resample 57, 64, DirectSoundWaveData_trinity_cymbal_crash, 255, 246, 0, 214
	voice_directsound_no_resample 55, 117, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 16
	voice_directsound_no_resample 58, 30, DirectSoundWaveData_trinity_cymbal_crash, 255, 250, 0, 216
	voice_directsound_no_resample 59, 20, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 250, 0, 226
	voice_directsound_no_resample 60, 30, DirectSoundWaveData_dance_drums_ride_bell, 255, 250, 0, 232
	voice_directsound_no_resample 60, 58, DirectSoundWaveData_sc88pro_tambourine, 255, 0, 255, 32
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_trinity_cymbal_crash, 255, 250, 0, 226
	voice_directsound_no_resample 60, 110, DirectSoundWaveData_sd90_cowbell, 255, 0, 255, 176
	voice_directsound_no_resample 60, 36, DirectSoundWaveData_trinity_cymbal_crash, 255, 250, 0, 216
	voice_directsound_no_resample 61, 102, DirectSoundWaveData_trinity_cymbal_crash, 255, 250, 0, 216
	voice_directsound_no_resample 60, 86, DirectSoundWaveData_trinity_cymbal_crash, 255, 250, 0, 216
	voice_directsound_no_resample 60, 90, DirectSoundWaveData_drum_and_percussion_kick, 255, 0, 255, 176
	voice_directsound_no_resample 57, 90, DirectSoundWaveData_drum_and_percussion_kick, 255, 0, 255, 176
	voice_directsound_no_resample 60, 20, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 0, 255, 176
	voice_directsound_no_resample 60, 24, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 176
	voice_directsound_no_resample 57, 26, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 176
	voice_directsound_no_resample 60, 26, DirectSoundWaveData_ethnic_flavours_ohtsuzumi, 255, 0, 255, 176
	voice_directsound_no_resample 60, 101, DirectSoundWaveData_ethnic_flavours_ohtsuzumi, 255, 0, 255, 176
	voice_directsound 60, 46, DirectSoundWaveData_sc88pro_fingered_bass, 255, 243, 0, 140
	voice_directsound_no_resample 60, 100, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 0, 255, 176
	voice_directsound_no_resample 60, 98, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 176
	voice_directsound_no_resample 63, 102, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 176
	voice_directsound_no_resample 60, 25, DirectSoundWaveData_unused_heart_of_asia_indian_drum, 255, 0, 255, 16
	voice_directsound_no_resample 60, 112, DirectSoundWaveData_ethnic_flavours_hyoushigi, 255, 0, 255, 16
	voice_directsound_no_resample 57, 100, DirectSoundWaveData_ethnic_flavours_hyoushigi, 255, 0, 255, 16
	voice_directsound_no_resample 55, 34, DirectSoundWaveData_ethnic_flavours_hyoushigi, 255, 0, 255, 16
	voice_directsound_no_resample 52, 22, DirectSoundWaveData_ethnic_flavours_hyoushigi, 255, 0, 255, 16
	voice_directsound_no_resample 59, 34, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 176
	voice_directsound_no_resample 56, 90, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 176
	voice_directsound_no_resample 54, 20, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 0
	voice_directsound_no_resample 60, 107, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 0
	voice_directsound 64, 44, DirectSoundWaveData_sd90_open_triangle, 255, 130, 150, 50
	voice_directsound 61, 44, DirectSoundWaveData_sd90_open_triangle, 255, 200, 130, 0
	voice_directsound 60, 46, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 243, 111, 64
	voice_directsound_no_resample 60, 94, DirectSoundWaveData_unused_sd90_oboe, 255, 0, 255, 226
	voice_directsound_no_resample 70, 26, DirectSoundWaveData_ethnic_flavours_ohtsuzumi, 255, 0, 255, 176
	voice_directsound_no_resample 54, 101, DirectSoundWaveData_ethnic_flavours_ohtsuzumi, 255, 0, 255, 176
	voice_directsound_no_resample 65, 101, DirectSoundWaveData_ethnic_flavours_ohtsuzumi, 255, 0, 255, 176
	voice_directsound_no_resample 60, 20, DirectSoundWaveData_sc88pro_fingered_bass, 255, 0, 255, 176
	voice_directsound_no_resample 60, 20, DirectSoundWaveData_sd90_cowbell, 255, 255, 191, 238
	voice_directsound_no_resample 48, 64, DirectSoundWaveData_sc88pro_synth_bass, 2, 0, 255, 16
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_trinity_30303_mega_bass, 255, 0, 255, 0
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_slap_bass, 255, 0, 255, 176
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 0
	voice_directsound_no_resample 60, 70, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 228, 127, 0
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_slap_bass, 255, 0, 227, 32
	voice_directsound_no_resample 60, 58, DirectSoundWaveData_unknown_snare, 255, 222, 0, 64
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_fretless_bass, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_slap_bass, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sd90_classical_oboe, 255, 255, 191, 16
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_trumpet_60, 255, 255, 191, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_trumpet_72, 255, 255, 191, 32
	voice_directsound_no_resample 48, 30, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 32
	voice_directsound_no_resample 60, 82, DirectSoundWaveData_unknown_close_hihat, 255, 0, 227, 32
	voice_directsound_no_resample 53, 40, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 32
	voice_directsound_no_resample 60, 82, DirectSoundWaveData_sc88pro_glockenspiel, 255, 0, 227, 32
	voice_directsound_no_resample 60, 50, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 32
	voice_directsound_no_resample 60, 82, DirectSoundWaveData_unknown_open_hihat, 254, 235, 0, 32
	voice_directsound_no_resample 66, 90, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 32
	voice_directsound_no_resample 72, 100, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 32
	voice_directsound_no_resample 57, 64, DirectSoundWaveData_trinity_cymbal_crash, 255, 247, 0, 216
	voice_directsound_no_resample 74, 110, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 16
	voice_directsound_no_resample 58, 30, DirectSoundWaveData_trinity_cymbal_crash, 255, 250, 0, 216
