voicegroup201::
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp                         , 255, 242,  51, 242  
    voice_square_2 60,  0,   0, 0, 9, 9, 1
	voice_square_1 60, 0,  0,  3, 0, 1, 4, 1
	voice_keysplit voicegroup005, KeySplitTable1
	voice_keysplit_all voicegroup199
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass                , 255, 253,   0, 188  
 	voice_noise 60, 0, 0, 0, 1, 0, 1
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs           , 255,   0, 255,   0  

	