#ifndef GUARD_CONSTANTS_APRICORN_TREE_H
#define GUARD_CONSTANTS_APRICORN_TREE_H

// Apricorns
#define APRICORN_RED       0
#define APRICORN_BLUE      1
#define APRICORN_YELLOW    2
#define APRICORN_GREEN     3
#define APRICORN_PINK      4
#define APRICORN_WHITE     5
#define APRICORN_BLACK     6

#define APRICORN_COUNT     7

// Trees
#define APRICORN_TREE_NONE 0

#define APRICORN_TREE_ROUTE101_RED_SAPLING 1
#define APRICORN_TREE_ROUTE38_WHITE_TREE 2
#define APRICORN_TREE_ROUTE26_BLUE_SAPLING 3
#define APRICORN_TREE_ROUTE29_GREEN_SAPLING 4
#define APRICORN_TREE_ROUTE30_GREEN_SAPLING 5
#define APRICORN_TREE_ROUTE30_PINK_TREE 6
#define APRICORN_TREE_ROUTE31_BLACK_SAPLING 7
#define APRICORN_TREE_VIOLET_BLACK_TREE 8
#define APRICORN_TREE_VIOLET_YELLOW_SAPLING 9
#define APRICORN_TREE_ROUTE33_BLACK_SAPLING 10
#define APRICORN_TREE_ROUTE31_PINK_SAPLING 11
#define APRICORN_TREE_AZALEA_WHITE_TREE 12
#define APRICORN_TREE_ROUTE35_GREEN_SAPLING 13
#define APRICORN_TREE_ROUTE35_BLUE_SAPLING 14
#define APRICORN_TREE_ROUTE37_RED_TREE 15
#define APRICORN_TREE_ROUTE37_BLACK_SAPLING 16
#define APRICORN_TREE_ROUTE37_BLUE_SAPLING 17
#define APRICORN_TREE_ROUTE39_GREEN_SAPLING 18
#define APRICORN_TREE_ROUTE42_GREEN_SAPLING 19
#define APRICORN_TREE_ROUTE42_PINK_TREE 20
#define APRICORN_TREE_ROUTE42_YELLOW_TREE 21
#define APRICORN_TREE_ROUTE43_BLACK_SAPLING 22
#define APRICORN_TREE_ROUTE44_RED_SAPLING 23
#define APRICORN_TREE_ROUTE45_BLUE_SAPLING 24
#define APRICORN_TREE_ROUTE45_YELLOW_SAPLING 25
#define APRICORN_TREE_ROUTE45_RED_TREE 26
#define APRICORN_TREE_ROUTE46_PINK_TREE 27
#define APRICORN_TREE_ROUTE46_GREEN_SAPLING 28
#define APRICORN_TREE_ROUTE33_PINK_SAPLING 29
#define APRICORN_TREE_ROUTE36_BLUE_SAPLING 30
#define APRICORN_TREE_ROUTE2_YELLOW_SAPLING 31
#define APRICORN_TREE_ROUTE2_PINK_SAPLING 32
#define APRICORN_TREE_ROUTE2_BLUE_SAPLING 33
#define APRICORN_TREE_ROUTE2_WHITE_TREE 34
#define APRICORN_TREE_ROUTE2_GREEN_TREE 35
#define APRICORN_TREE_ROUTE4_BLACK_TREE 36
#define APRICORN_TREE_ROUTE5_RED_SAPLING 37
#define APRICORN_TREE_ROUTE7_BLUE_SAPLING 38
#define APRICORN_TREE_ROUTE7_YELLOW_SAPLING 39

#define APRICORN_TREE_COUNT 40

#endif //GUARD_CONSTANTS_APRICORN_TREE_H
