#ifndef GUARD_REGIONMAPSEC_H
#define GUARD_REGIONMAPSEC_H

// Flyable locations
#define MAPSEC_LITTLEROOT_TOWN              0x0000
#define MAPSEC_OLDALE_TOWN                  0x0001
#define MAPSEC_DEWFORD_TOWN                 0x0002
#define MAPSEC_LAVARIDGE_TOWN               0x0003
#define MAPSEC_FALLARBOR_TOWN               0x0004
#define MAPSEC_VERDANTURF_TOWN              0x0005
#define MAPSEC_PACIFIDLOG_TOWN              0x0006
#define MAPSEC_PETALBURG_CITY               0x0007
#define MAPSEC_SLATEPORT_CITY               0x0008
#define MAPSEC_MAUVILLE_CITY                0x0009
#define MAPSEC_RUSTBORO_CITY                0x000A
#define MAPSEC_FORTREE_CITY                 0x000B
#define MAPSEC_LILYCOVE_CITY                0x000C
#define MAPSEC_MOSSDEEP_CITY                0x000D
#define MAPSEC_SOOTOPOLIS_CITY              0x000E
#define MAPSEC_EVER_GRANDE_CITY             0x000F
#define MAPSEC_PALLET_TOWN                  0x0010
#define MAPSEC_VIRIDIAN_CITY                0x0011
#define MAPSEC_PEWTER_CITY                  0x0012
#define MAPSEC_CERULEAN_CITY                0x0013
#define MAPSEC_LAVENDER_TOWN                0x0014
#define MAPSEC_VERMILION_CITY               0x0015
#define MAPSEC_CELADON_CITY                 0x0016
#define MAPSEC_FUCHSIA_CITY                 0x0017
#define MAPSEC_CINNABAR_ISLAND              0x0018
#define MAPSEC_INDIGO_PLATEAU               0x0019
#define MAPSEC_SAFFRON_CITY                 0x001A
#define MAPSEC_NEWBARK                      0x0020
#define MAPSEC_CHERRYGROVE                  0x0021
#define MAPSEC_VIOLET                       0x0022
#define MAPSEC_AZALEA                       0x0023
#define MAPSEC_GOLDENROD                    0x0024
#define MAPSEC_OLIVINE                      0x0025
#define MAPSEC_CYANWOOD                     0x0026
#define MAPSEC_ECRUTEAK                     0x0027
#define MAPSEC_MAHOGANY                     0x0028
#define MAPSEC_LAROUSSE                     0x0029
#define MAPSEC_ASHLEAF                      0x0030
#define MAPSEC_KASADO                       0x0031
#define MAPSEC_KUGA                         0x0032
#define MAPSEC_BLACKTHORN                   0x0033 // Re-order once all locations have been reviewed as flyable

#define MINIMAL_MAPSEC_FLYABLE_LOCATION     MAPSEC_LITTLEROOT_TOWN
#define MAXIMAL_MAPSEC_FLYABLE_LOCATION     MAPSEC_BLACKTHORN // Update to latest flyable locations


#define MAPSEC_ROUTE_101                    0x1000
#define MAPSEC_ROUTE_102                    0x1001
#define MAPSEC_ROUTE_103                    0x1002
#define MAPSEC_ROUTE_104                    0x1003
#define MAPSEC_ROUTE_105                    0x1004
#define MAPSEC_ROUTE_106                    0x1005
#define MAPSEC_ROUTE_107                    0x1006
#define MAPSEC_ROUTE_108                    0x1007
#define MAPSEC_ROUTE_109                    0x1008
#define MAPSEC_ROUTE_110                    0x1009
#define MAPSEC_ROUTE_111                    0x100A
#define MAPSEC_ROUTE_112                    0x100B
#define MAPSEC_ROUTE_113                    0x100C
#define MAPSEC_ROUTE_114                    0x100D
#define MAPSEC_ROUTE_115                    0x100E
#define MAPSEC_ROUTE_116                    0x100F
#define MAPSEC_ROUTE_117                    0x1010
#define MAPSEC_ROUTE_118                    0x1011
#define MAPSEC_ROUTE_119                    0x1012
#define MAPSEC_ROUTE_120                    0x1013
#define MAPSEC_ROUTE_121                    0x1014
#define MAPSEC_ROUTE_122                    0x1015
#define MAPSEC_ROUTE_123                    0x1016
#define MAPSEC_ROUTE_124                    0x1017
#define MAPSEC_ROUTE_125                    0x1018
#define MAPSEC_ROUTE_126                    0x1019
#define MAPSEC_ROUTE_127                    0x101A
#define MAPSEC_ROUTE_128                    0x101B
#define MAPSEC_ROUTE_129                    0x101C
#define MAPSEC_ROUTE_130                    0x101D
#define MAPSEC_ROUTE_131                    0x101E
#define MAPSEC_ROUTE_132                    0x101F
#define MAPSEC_ROUTE_133                    0x1020
#define MAPSEC_ROUTE_134                    0x1021
#define MAPSEC_UNDERWATER_124               0x1022
#define MAPSEC_UNDERWATER_126               0x1023
#define MAPSEC_UNDERWATER_127               0x1024
#define MAPSEC_UNDERWATER_128               0x1025
#define MAPSEC_UNDERWATER_SOOTOPOLIS        0x1026
#define MAPSEC_GRANITE_CAVE                 0x1027
#define MAPSEC_MT_CHIMNEY                   0x1028
#define MAPSEC_SAFARI_ZONE                  0x1029
#define MAPSEC_BATTLE_FRONTIER              0x102A
#define MAPSEC_PETALBURG_WOODS              0x102B
#define MAPSEC_RUSTURF_TUNNEL               0x102C
#define MAPSEC_ABANDONED_SHIP               0x102D
#define MAPSEC_NEW_MAUVILLE                 0x102E
#define MAPSEC_METEOR_FALLS                 0x102F
#define MAPSEC_METEOR_FALLS2                0x1030
#define MAPSEC_MT_PYRE                      0x1031
#define MAPSEC_AQUA_HIDEOUT_OLD             0x1032
#define MAPSEC_SHOAL_CAVE                   0x1033
#define MAPSEC_SEAFLOOR_CAVERN              0x1034
#define MAPSEC_UNDERWATER_SEAFLOOR_CAVERN   0x1035
#define MAPSEC_VICTORY_ROAD                 0x1036
#define MAPSEC_MIRAGE_ISLAND                0x1037
#define MAPSEC_CAVE_OF_ORIGIN               0x1038
#define MAPSEC_SOUTHERN_ISLAND              0x1039
#define MAPSEC_FIERY_PATH                   0x103A
#define MAPSEC_FIERY_PATH2                  0x103B
#define MAPSEC_JAGGED_PASS                  0x103C
#define MAPSEC_JAGGED_PASS2                 0x103D
#define MAPSEC_SEALED_CHAMBER               0x103E
#define MAPSEC_UNDERWATER_SEALED_CHAMBER    0x103F
#define MAPSEC_SCORCHED_SLAB                0x1040
#define MAPSEC_ISLAND_CAVE                  0x1041
#define MAPSEC_DESERT_RUINS                 0x1042
#define MAPSEC_ANCIENT_TOMB                 0x1043
#define MAPSEC_INSIDE_OF_TRUCK              0x1044
#define MAPSEC_SKY_PILLAR                   0x1045
#define MAPSEC_SECRET_BASE                  0x1046
#define MAPSEC_DYNAMIC                      0x1047
#define MAPSEC_ROUTE_4_POKECENTER           0x1048
#define MAPSEC_ROUTE_10_POKECENTER          0x1049
#define MAPSEC_ROUTE_1                      0x104A
#define MAPSEC_ROUTE_2                      0x104B
#define MAPSEC_ROUTE_3                      0x104C
#define MAPSEC_ROUTE_4                      0x104D
#define MAPSEC_ROUTE_5                      0x104E
#define MAPSEC_ROUTE_6                      0x104F
#define MAPSEC_ROUTE_7                      0x1050
#define MAPSEC_ROUTE_8                      0x1051
#define MAPSEC_ROUTE_9                      0x1052
#define MAPSEC_ROUTE_10                     0x1053
#define MAPSEC_ROUTE_11                     0x1054
#define MAPSEC_ROUTE_12                     0x1055
#define MAPSEC_ROUTE_13                     0x1056
#define MAPSEC_ROUTE_14                     0x1057
#define MAPSEC_ROUTE_15                     0x1058
#define MAPSEC_ROUTE_16                     0x1059
#define MAPSEC_ROUTE_17                     0x105A
#define MAPSEC_ROUTE_18                     0x105B
#define MAPSEC_ROUTE_19                     0x105C
#define MAPSEC_ROUTE_20                     0x105D
#define MAPSEC_ROUTE_21                     0x105E
#define MAPSEC_ROUTE_22                     0x105F
#define MAPSEC_ROUTE_23                     0x1060
#define MAPSEC_ROUTE_24                     0x1061
#define MAPSEC_ROUTE_25                     0x1062
#define MAPSEC_VIRIDIAN_FOREST              0x1063
#define MAPSEC_MT_MOON                      0x1064
#define MAPSEC_S_S_ANNE                     0x1065
#define MAPSEC_UNDERGROUND_PATH             0x1066
#define MAPSEC_UNDERGROUND_PATH_2           0x1067
#define MAPSEC_DIGLETTS_CAVE                0x1068
#define MAPSEC_KANTO_VICTORY_ROAD           0x1069
#define MAPSEC_ROCKET_HIDEOUT               0x106A
#define MAPSEC_SILPH_CO                     0x106B
#define MAPSEC_POKEMON_MANSION              0x106C
#define MAPSEC_KANTO_SAFARI_ZONE            0x106D
#define MAPSEC_POKEMON_LEAGUE               0x106E
#define MAPSEC_ROCK_TUNNEL                  0x106F
#define MAPSEC_SEAFOAM_ISLANDS              0x1070
#define MAPSEC_POKEMON_TOWER                0x1071
#define MAPSEC_CERULEAN_CAVE                0x1072
#define MAPSEC_POWER_PLANT                  0x1073
#define MAPSEC_ONE_ISLAND                   0x1074
#define MAPSEC_TWO_ISLAND                   0x1075
#define MAPSEC_THREE_ISLAND                 0x1076
#define MAPSEC_FOUR_ISLAND                  0x1077
#define MAPSEC_FIVE_ISLAND                  0x1078
#define MAPSEC_SEVEN_ISLAND                 0x1079
#define MAPSEC_SIX_ISLAND                   0x107A
#define MAPSEC_KINDLE_ROAD                  0x107B
#define MAPSEC_TREASURE_BEACH               0x107C
#define MAPSEC_CAPE_BRINK                   0x107D
#define MAPSEC_BOND_BRIDGE                  0x107E
#define MAPSEC_THREE_ISLE_PORT              0x107F
#define MAPSEC_SEVII_ISLE_6                 0x1080
#define MAPSEC_SEVII_ISLE_7                 0x1081
#define MAPSEC_SEVII_ISLE_8                 0x1082
#define MAPSEC_SEVII_ISLE_9                 0x1083
#define MAPSEC_RESORT_GORGEOUS              0x1084
#define MAPSEC_WATER_LABYRINTH              0x1085
#define MAPSEC_FIVE_ISLE_MEADOW             0x1086
#define MAPSEC_MEMORIAL_PILLAR              0x1087
#define MAPSEC_OUTCAST_ISLAND               0x1088
#define MAPSEC_GREEN_PATH                   0x1089
#define MAPSEC_WATER_PATH                   0x108A
#define MAPSEC_RUIN_VALLEY                  0x108B
#define MAPSEC_TRAINER_TOWER                0x108C
#define MAPSEC_CANYON_ENTRANCE              0x108D
#define MAPSEC_SEVAULT_CANYON               0x108E
#define MAPSEC_TANOBY_RUINS                 0x108F
#define MAPSEC_SEVII_ISLE_22                0x1090
#define MAPSEC_SEVII_ISLE_23                0x1091
#define MAPSEC_SEVII_ISLE_24                0x1092
#define MAPSEC_NAVEL_ROCK_FRLG              0x1093
#define MAPSEC_MT_EMBER                     0x1094
#define MAPSEC_BERRY_FOREST                 0x1095
#define MAPSEC_ICEFALL_CAVE                 0x1096
#define MAPSEC_ROCKET_WAREHOUSE             0x1097
#define MAPSEC_TRAINER_TOWER_2              0x1098
#define MAPSEC_DOTTED_HOLE                  0x1099
#define MAPSEC_LOST_CAVE                    0x109A
#define MAPSEC_PATTERN_BUSH                 0x109B
#define MAPSEC_ALTERING_CAVE_FRLG           0x109C
#define MAPSEC_TANOBY_CHAMBERS              0x109D
#define MAPSEC_THREE_ISLE_PATH              0x109E
#define MAPSEC_TANOBY_KEY                   0x109F
#define MAPSEC_BIRTH_ISLAND_FRLG            0x10A0
#define MAPSEC_MONEAN_CHAMBER               0x10A1
#define MAPSEC_LIPTOO_CHAMBER               0x10A2
#define MAPSEC_WEEPTH_CHAMBER               0x10A3
#define MAPSEC_DILFORD_CHAMBER              0x10A4
#define MAPSEC_SCUFIB_CHAMBER               0x10A5
#define MAPSEC_RIXY_CHAMBER                 0x10A6
#define MAPSEC_VIAPOIS_CHAMBER              0x10A7
#define MAPSEC_EMBER_SPA                    0x10A8
#define MAPSEC_SPECIAL_AREA                 0x10A9
#define MAPSEC_AQUA_HIDEOUT                 0x10AA
#define MAPSEC_MAGMA_HIDEOUT                0x10AB
#define MAPSEC_MIRAGE_TOWER                 0x10AC
#define MAPSEC_BIRTH_ISLAND                 0x10AD
#define MAPSEC_FARAWAY_ISLAND               0x10AE
#define MAPSEC_ARTISAN_CAVE                 0x10AF
#define MAPSEC_MARINE_CAVE                  0x10B0
#define MAPSEC_UNDERWATER_MARINE_CAVE       0x10B1
#define MAPSEC_TERRA_CAVE                   0x10B2
#define MAPSEC_UNDERWATER_105               0x10B3
#define MAPSEC_UNDERWATER_125               0x10B4
#define MAPSEC_UNDERWATER_129               0x10B5
#define MAPSEC_DESERT_UNDERPASS             0x10B6
#define MAPSEC_ALTERING_CAVE                0x10B7
#define MAPSEC_NAVEL_ROCK                   0x10B8
#define MAPSEC_TRAINER_HILL                 0x10B9
#define MAPSEC_LAKE_OF_RAGE                 0x10BA
#define MAPSEC_ROUTE_32                     0x10BB
#define MAPSEC_CROSSGATE                    0x10BC
#define MAPSEC_BLUEFIN                      0x10BD
#define MAPSEC_BATTLE_TOWER                 0x10BE
#define MAPSEC_ROUTE_26                     0x10BF
#define MAPSEC_ROUTE_27                     0x10C0
#define MAPSEC_ROUTE_28                     0x10C1
#define MAPSEC_ROUTE_29                     0x10C2
#define MAPSEC_ROUTE_30                     0x10C3
#define MAPSEC_ROUTE_31                     0x10C4
#define MAPSEC_ROUTE_33                     0x10C5
#define MAPSEC_ROUTE_34                     0x10C6
#define MAPSEC_ROUTE_35                     0x10C7
#define MAPSEC_ROUTE_36                     0x10C8
#define MAPSEC_ROUTE_37                     0x10C9
#define MAPSEC_ROUTE_38                     0x10CA
#define MAPSEC_ROUTE_39                     0x10CB
#define MAPSEC_ROUTE_40                     0x10CC
#define MAPSEC_ROUTE_41                     0x10CD
#define MAPSEC_ROUTE_42                     0x10CE
#define MAPSEC_ROUTE_43                     0x10CF
#define MAPSEC_ROUTE_44                     0x10D0
#define MAPSEC_ROUTE_45                     0x10D1
#define MAPSEC_ROUTE_46                     0x10D2
#define MAPSEC_ROUTE_47                     0x10D3
#define MAPSEC_ROUTE_48                     0x10D4
#define MAPSEC_ROUTE_100                    0x10D5
#define MAPSEC_GATE                         0x10D6
#define MAPSEC_JOHTO_SAFARI                 0x10D7
#define MAPSEC_DRAGONSDEN                   0x10D8
#define MAPSEC_RUINS_OF_ALPH                0x10D9
#define MAPSEC_MTSILVER                     0x10DA
#define MAPSEC_MTMORTAR                     0x10DB
#define MAPSEC_ICE_PATH                     0x10DC
#define MAPSEC_DARK_CAVE                    0x10DD
#define MAPSEC_UNION_CAVE                   0x10DE
#define MAPSEC_ILEX_FOREST                  0x10DF
#define MAPSEC_TINTOWER                     0x10E0
#define MAPSEC_NATIONAL_PARK                0x10E1
#define MAPSEC_SLOWPOKE_WELL                0x10E2
#define MAPSEC_SPROUTTOWER                  0x10E3
#define MAPSEC_BURNEDTOWER                  0x10E4
#define MAPSEC_TOHJO_FALLS                  0x10E5
#define MAPSEC_OLIVINE_LIGHTHOUSE           0x10E6
#define MAPSEC_WHIRL                        0x10E7
#define MAPSEC_ROUTE_98                     0x10E8
#define MAPSEC_ROUTE_99                     0x10E9
#define MAPSEC_ROUTE_135                    0x10EA
#define MAPSEC_ROUTE_136                    0x10EB
#define MAPSEC_ROUTE_137                    0x10EC
#define MAPSEC_ROUTE_138                    0x10ED
#define MAPSEC_CINNABAR_LAB                 0x10EE
#define MAPSEC_ROUTE_49                     0x10EF
#define MAPSEC_ROUTE_50                     0x10F0
#define MAPSEC_COBALT_BEACH                 0x10F1
#define MAPSEC_ROUTE_139                    0x10F2
#define MAPSEC_OLDROOT                      0x10F3
#define MAPSEC_DEWFORD_FOREST               0x10F4
#define MAPSEC_CINNABAR_VOLCANO             0x10F5
#define MAPSEC_WHITESTONE                   0x10F6
#define MAPSEC_SILVER_STRAIT                0x10F7
#define MAPSEC_ROUTE_51                     0x10F8
#define MAPSEC_ROUTE_52                     0x10F9
#define MAPSEC_VIRIDIAN_LAKE                0x10FA
#define MAPSEC_VIRIDIAN_LAKE_UNDERWATER     0x10FB
#define MAPSEC_CINNABAR_UNDERWATER          0x10FC
#define MAPSEC_ROUTE_119_UNDERWATER         0x10FD
#define MAPSEC_ROUTE_24_UNDERWATER          0x10FE
#define MAPSEC_JOHTO_ROCKET_HIDEOUT         0x10FF
#define MAPSEC_MISTY_CAVE                   0x1100

#define MAPSEC_NONE                         0xFFFC
#define METLOC_SPECIAL_EGG                  0xFFFD
#define METLOC_IN_GAME_TRADE                0xFFFE
#define METLOC_FATEFUL_ENCOUNTER            0xFFFF

#define KANTO_MAPSEC_START  MAPSEC_PALLET_TOWN
#define KANTO_MAPSEC_END    MAPSEC_SPECIAL_AREA
#define KANTO_MAPSEC_COUNT (KANTO_MAPSEC_END - KANTO_MAPSEC_START + 1)

#endif //GUARD_REGIONMAPSEC_H
