#ifndef GUARD_REGIONMAPSEC_H
#define GUARD_REGIONMAPSEC_H

#define MAPSEC_LITTLEROOT_TOWN              0x0000
#define MAPSEC_OLDALE_TOWN                  0x0001
#define MAPSEC_DEWFORD_TOWN                 0x0002
#define MAPSEC_LAVARIDGE_TOWN               0x0003
#define MAPSEC_FALLARBOR_TOWN               0x0004
#define MAPSEC_VERDANTURF_TOWN              0x0005
#define MAPSEC_PACIFIDLOG_TOWN              0x0006
#define MAPSEC_PETALBURG_CITY               0x0007
#define MAPSEC_SLATEPORT_CITY               0x0008
#define MAPSEC_MAUVILLE_CITY                0x0009
#define MAPSEC_RUSTBORO_CITY                0x000A
#define MAPSEC_FORTREE_CITY                 0x000B
#define MAPSEC_LILYCOVE_CITY                0x000C
#define MAPSEC_MOSSDEEP_CITY                0x000D
#define MAPSEC_SOOTOPOLIS_CITY              0x000E
#define MAPSEC_EVER_GRANDE_CITY             0x000F
#define MAPSEC_ROUTE_101                    0x0010
#define MAPSEC_ROUTE_102                    0x0011
#define MAPSEC_ROUTE_103                    0x0012
#define MAPSEC_ROUTE_104                    0x0013
#define MAPSEC_ROUTE_105                    0x0014
#define MAPSEC_ROUTE_106                    0x0015
#define MAPSEC_ROUTE_107                    0x0016
#define MAPSEC_ROUTE_108                    0x0017
#define MAPSEC_ROUTE_109                    0x0018
#define MAPSEC_ROUTE_110                    0x0019
#define MAPSEC_ROUTE_111                    0x001A
#define MAPSEC_ROUTE_112                    0x001B
#define MAPSEC_ROUTE_113                    0x001C
#define MAPSEC_ROUTE_114                    0x001D
#define MAPSEC_ROUTE_115                    0x001E
#define MAPSEC_ROUTE_116                    0x001F
#define MAPSEC_ROUTE_117                    0x0020
#define MAPSEC_ROUTE_118                    0x0021
#define MAPSEC_ROUTE_119                    0x0022
#define MAPSEC_ROUTE_120                    0x0023
#define MAPSEC_ROUTE_121                    0x0024
#define MAPSEC_ROUTE_122                    0x0025
#define MAPSEC_ROUTE_123                    0x0026
#define MAPSEC_ROUTE_124                    0x0027
#define MAPSEC_ROUTE_125                    0x0028
#define MAPSEC_ROUTE_126                    0x0029
#define MAPSEC_ROUTE_127                    0x002A
#define MAPSEC_ROUTE_128                    0x002B
#define MAPSEC_ROUTE_129                    0x002C
#define MAPSEC_ROUTE_130                    0x002D
#define MAPSEC_ROUTE_131                    0x002E
#define MAPSEC_ROUTE_132                    0x002F
#define MAPSEC_ROUTE_133                    0x0030
#define MAPSEC_ROUTE_134                    0x0031
#define MAPSEC_UNDERWATER_124               0x0032
#define MAPSEC_UNDERWATER_126               0x0033
#define MAPSEC_UNDERWATER_127               0x0034
#define MAPSEC_UNDERWATER_128               0x0035
#define MAPSEC_UNDERWATER_SOOTOPOLIS        0x0036
#define MAPSEC_GRANITE_CAVE                 0x0037
#define MAPSEC_MT_CHIMNEY                   0x0038
#define MAPSEC_SAFARI_ZONE                  0x0039
#define MAPSEC_BATTLE_FRONTIER              0x003A
#define MAPSEC_PETALBURG_WOODS              0x003B
#define MAPSEC_RUSTURF_TUNNEL               0x003C
#define MAPSEC_ABANDONED_SHIP               0x003D
#define MAPSEC_NEW_MAUVILLE                 0x003E
#define MAPSEC_METEOR_FALLS                 0x003F
#define MAPSEC_METEOR_FALLS2                0x0040
#define MAPSEC_MT_PYRE                      0x0041
#define MAPSEC_AQUA_HIDEOUT_OLD             0x0042
#define MAPSEC_SHOAL_CAVE                   0x0043
#define MAPSEC_SEAFLOOR_CAVERN              0x0044
#define MAPSEC_UNDERWATER_SEAFLOOR_CAVERN   0x0045
#define MAPSEC_VICTORY_ROAD                 0x0046
#define MAPSEC_MIRAGE_ISLAND                0x0047
#define MAPSEC_CAVE_OF_ORIGIN               0x0048
#define MAPSEC_SOUTHERN_ISLAND              0x0049
#define MAPSEC_FIERY_PATH                   0x004A
#define MAPSEC_FIERY_PATH2                  0x004B
#define MAPSEC_JAGGED_PASS                  0x004C
#define MAPSEC_JAGGED_PASS2                 0x004D
#define MAPSEC_SEALED_CHAMBER               0x004E
#define MAPSEC_UNDERWATER_SEALED_CHAMBER    0x004F
#define MAPSEC_SCORCHED_SLAB                0x0050
#define MAPSEC_ISLAND_CAVE                  0x0051
#define MAPSEC_DESERT_RUINS                 0x0052
#define MAPSEC_ANCIENT_TOMB                 0x0053
#define MAPSEC_INSIDE_OF_TRUCK              0x0054
#define MAPSEC_SKY_PILLAR                   0x0055
#define MAPSEC_SECRET_BASE                  0x0056
#define MAPSEC_DYNAMIC                      0x0057
#define MAPSEC_PALLET_TOWN                  0x0058
#define MAPSEC_VIRIDIAN_CITY                0x0059
#define MAPSEC_PEWTER_CITY                  0x005A
#define MAPSEC_CERULEAN_CITY                0x005B
#define MAPSEC_LAVENDER_TOWN                0x005C
#define MAPSEC_VERMILION_CITY               0x005D
#define MAPSEC_CELADON_CITY                 0x005E
#define MAPSEC_FUCHSIA_CITY                 0x005F
#define MAPSEC_CINNABAR_ISLAND              0x0060
#define MAPSEC_INDIGO_PLATEAU               0x0061
#define MAPSEC_SAFFRON_CITY                 0x0062
#define MAPSEC_ROUTE_4_POKECENTER           0x0063
#define MAPSEC_ROUTE_10_POKECENTER          0x0064
#define MAPSEC_ROUTE_1                      0x0065
#define MAPSEC_ROUTE_2                      0x0066
#define MAPSEC_ROUTE_3                      0x0067
#define MAPSEC_ROUTE_4                      0x0068
#define MAPSEC_ROUTE_5                      0x0069
#define MAPSEC_ROUTE_6                      0x006A
#define MAPSEC_ROUTE_7                      0x006B
#define MAPSEC_ROUTE_8                      0x006C
#define MAPSEC_ROUTE_9                      0x006D
#define MAPSEC_ROUTE_10                     0x006E
#define MAPSEC_ROUTE_11                     0x006F
#define MAPSEC_ROUTE_12                     0x0070
#define MAPSEC_ROUTE_13                     0x0071
#define MAPSEC_ROUTE_14                     0x0072
#define MAPSEC_ROUTE_15                     0x0073
#define MAPSEC_ROUTE_16                     0x0074
#define MAPSEC_ROUTE_17                     0x0075
#define MAPSEC_ROUTE_18                     0x0076
#define MAPSEC_ROUTE_19                     0x0077
#define MAPSEC_ROUTE_20                     0x0078
#define MAPSEC_ROUTE_21                     0x0079
#define MAPSEC_ROUTE_22                     0x007A
#define MAPSEC_ROUTE_23                     0x007B
#define MAPSEC_ROUTE_24                     0x007C
#define MAPSEC_ROUTE_25                     0x007D
#define MAPSEC_VIRIDIAN_FOREST              0x007E
#define MAPSEC_MT_MOON                      0x007F
#define MAPSEC_S_S_ANNE                     0x0080
#define MAPSEC_UNDERGROUND_PATH             0x0081
#define MAPSEC_UNDERGROUND_PATH_2           0x0082
#define MAPSEC_DIGLETTS_CAVE                0x0083
#define MAPSEC_KANTO_VICTORY_ROAD           0x0084
#define MAPSEC_ROCKET_HIDEOUT               0x0085
#define MAPSEC_SILPH_CO                     0x0086
#define MAPSEC_POKEMON_MANSION              0x0087
#define MAPSEC_KANTO_SAFARI_ZONE            0x0088
#define MAPSEC_POKEMON_LEAGUE               0x0089
#define MAPSEC_ROCK_TUNNEL                  0x008A
#define MAPSEC_SEAFOAM_ISLANDS              0x008B
#define MAPSEC_POKEMON_TOWER                0x008C
#define MAPSEC_CERULEAN_CAVE                0x008D
#define MAPSEC_POWER_PLANT                  0x008E
#define MAPSEC_ONE_ISLAND                   0x008F
#define MAPSEC_TWO_ISLAND                   0x0090
#define MAPSEC_THREE_ISLAND                 0x0091
#define MAPSEC_FOUR_ISLAND                  0x0092
#define MAPSEC_FIVE_ISLAND                  0x0093
#define MAPSEC_SEVEN_ISLAND                 0x0094
#define MAPSEC_SIX_ISLAND                   0x0095
#define MAPSEC_KINDLE_ROAD                  0x0096
#define MAPSEC_TREASURE_BEACH               0x0097
#define MAPSEC_CAPE_BRINK                   0x0098
#define MAPSEC_BOND_BRIDGE                  0x0099
#define MAPSEC_THREE_ISLE_PORT              0x009A
#define MAPSEC_SEVII_ISLE_6                 0x009B
#define MAPSEC_SEVII_ISLE_7                 0x009C
#define MAPSEC_SEVII_ISLE_8                 0x009D
#define MAPSEC_SEVII_ISLE_9                 0x009E
#define MAPSEC_RESORT_GORGEOUS              0x009F
#define MAPSEC_WATER_LABYRINTH              0x00A0
#define MAPSEC_FIVE_ISLE_MEADOW             0x00A1
#define MAPSEC_MEMORIAL_PILLAR              0x00A2
#define MAPSEC_OUTCAST_ISLAND               0x00A3
#define MAPSEC_GREEN_PATH                   0x00A4
#define MAPSEC_WATER_PATH                   0x00A5
#define MAPSEC_RUIN_VALLEY                  0x00A6
#define MAPSEC_TRAINER_TOWER                0x00A7
#define MAPSEC_CANYON_ENTRANCE              0x00A8
#define MAPSEC_SEVAULT_CANYON               0x00A9
#define MAPSEC_TANOBY_RUINS                 0x00AA
#define MAPSEC_SEVII_ISLE_22                0x00AB
#define MAPSEC_SEVII_ISLE_23                0x00AC
#define MAPSEC_SEVII_ISLE_24                0x00AD
#define MAPSEC_NAVEL_ROCK_FRLG              0x00AE
#define MAPSEC_MT_EMBER                     0x00AF
#define MAPSEC_BERRY_FOREST                 0x00B0
#define MAPSEC_ICEFALL_CAVE                 0x00B1
#define MAPSEC_ROCKET_WAREHOUSE             0x00B2
#define MAPSEC_TRAINER_TOWER_2              0x00B3
#define MAPSEC_DOTTED_HOLE                  0x00B4
#define MAPSEC_LOST_CAVE                    0x00B5
#define MAPSEC_PATTERN_BUSH                 0x00B6
#define MAPSEC_ALTERING_CAVE_FRLG           0x00B7
#define MAPSEC_TANOBY_CHAMBERS              0x00B8
#define MAPSEC_THREE_ISLE_PATH              0x00B9
#define MAPSEC_TANOBY_KEY                   0x00BA
#define MAPSEC_BIRTH_ISLAND_FRLG            0x00BB
#define MAPSEC_MONEAN_CHAMBER               0x00BC
#define MAPSEC_LIPTOO_CHAMBER               0x00BD
#define MAPSEC_WEEPTH_CHAMBER               0x00BE
#define MAPSEC_DILFORD_CHAMBER              0x00BF
#define MAPSEC_SCUFIB_CHAMBER               0x00C0
#define MAPSEC_RIXY_CHAMBER                 0x00C1
#define MAPSEC_VIAPOIS_CHAMBER              0x00C2
#define MAPSEC_EMBER_SPA                    0x00C3
#define MAPSEC_SPECIAL_AREA                 0x00C4
#define MAPSEC_AQUA_HIDEOUT                 0x00C5
#define MAPSEC_MAGMA_HIDEOUT                0x00C6
#define MAPSEC_MIRAGE_TOWER                 0x00C7
#define MAPSEC_BIRTH_ISLAND                 0x00C8
#define MAPSEC_FARAWAY_ISLAND               0x00C9
#define MAPSEC_ARTISAN_CAVE                 0x00CA
#define MAPSEC_MARINE_CAVE                  0x00CB
#define MAPSEC_UNDERWATER_MARINE_CAVE       0x00CC
#define MAPSEC_TERRA_CAVE                   0x00CD
#define MAPSEC_UNDERWATER_105               0x00CE
#define MAPSEC_UNDERWATER_125               0x00CF
#define MAPSEC_UNDERWATER_129               0x00D0
#define MAPSEC_DESERT_UNDERPASS             0x00D1
#define MAPSEC_ALTERING_CAVE                0x00D2
#define MAPSEC_NAVEL_ROCK                   0x00D3
#define MAPSEC_TRAINER_HILL                 0x00D4
#define MAPSEC_NEWBARK                      0x00D5
#define MAPSEC_CHERRYGROVE                  0x00D6
#define MAPSEC_VIOLET                       0x00D8
#define MAPSEC_AZALEA                       0x00D9
#define MAPSEC_GOLDENROD                    0x00DA
#define MAPSEC_OLIVINE                      0x00DB
#define MAPSEC_CYANWOOD                     0x00DC
#define MAPSEC_ECRUTEAK                     0x00DD
#define MAPSEC_MAHOGANY                     0x00DE
#define MAPSEC_BLACKTHORN                   0x00DF
#define MAPSEC_LAKE_OF_RAGE                 0x00E0
#define MAPSEC_ROUTE_32                     0x00E1
#define MAPSEC_CROSSGATE                    0x00E2
#define MAPSEC_BLUEFIN                      0x00E3
#define MAPSEC_BATTLE_TOWER                 0x00E4
#define MAPSEC_ROUTE_28                     0x00E5
#define MAPSEC_NONE                         0x00E6

#define METLOC_SPECIAL_EGG                  0x00FD
#define METLOC_IN_GAME_TRADE                0x00FE
#define METLOC_FATEFUL_ENCOUNTER            0x00FF

#define KANTO_MAPSEC_START  MAPSEC_PALLET_TOWN
#define KANTO_MAPSEC_END    MAPSEC_SPECIAL_AREA
#define KANTO_MAPSEC_COUNT (KANTO_MAPSEC_END - KANTO_MAPSEC_START + 1)

#endif //GUARD_REGIONMAPSEC_H
