MtMoonRoof_MapScripts::
	.byte 0

MtMoonRoof_EventScript_GameBoyKid1::
	msgbox MtMoonRoof_Text_GameBoyKid1, MSGBOX_NPC
	end

MtMoonRoof_Text_GameBoyKid1:
	.string "He used the MOONSTONE too soon...\n"
	.string "now it won’t learn the move it was\l"
	.string "supposed to.\p"
	.string "Some things need patience, even the moon\n"
	.string "takes its time to change.$"

MtMoonRoof_EventScript_GameBoyKid2::
	msgbox MtMoonRoof_Text_GameBoyKid2, MSGBOX_NPC
	end

MtMoonRoof_Text_GameBoyKid2:
	.string "My friend says if you play up here during\n"
	.string "a full moon, CLEFAIRY shows up in your\l"
	.string "game...\p"
	.string "even if you didn’t catch one.\n"
	.string "But only if you don’t tell anyone.$"