ViridianLake_MapScripts::
	.byte 0

ViridianLake_Sign::
	msgbox ViridianLake_Text_Sign, MSGBOX_SIGN
	end

ViridianLake_Text_Sign:
	.string "VIRIDIAN LAKE\n"
	.string "“Still Waters, Timeless Secrets.”$"

ViridianLake_Trainer_Tips::
	msgbox ViridianLake_Text_Trainer_Tips, MSGBOX_SIGN
	end

ViridianLake_Text_Trainer_Tips:
	.string "TRAINER TIPS\p"
	.string "In thick FOG, accuracy drops; moves\n"
	.string "like AERIAL ACE and SHOCK WAVE never\p"
	.string "miss, so keep them handy if you want\n"
	.string "to find your way and win battles!$"

ViridianLake_Hydroelectric_Plant::
	msgbox ViridianLake_Text_Hydroelectric_Plant, MSGBOX_SIGN
	end

ViridianLake_Text_Hydroelectric_Plant:
	.string "HYDROELECTRIC PLANT$"

ViridianLake_Misty_Cave::
	msgbox ViridianLake_Text_Misty_Cave, MSGBOX_SIGN
	end

ViridianLake_Text_Misty_Cave:
	.string "MISTY CAVE$"

ViridianLake_Spearow_Farm::
	msgbox ViridianLake_Text_Spearow_Farm, MSGBOX_SIGN
	end

ViridianLake_Text_Spearow_Farm:
	.string "“SPEAROW FARM”$"

ViridianLake_EventScript_Farmer::
	msgbox ViridianLake_Text_Farmer, MSGBOX_NPC
	end

ViridianLake_Text_Farmer:
	.string "City folks don’t believe me,\n"
	.string "but my SPEAROWS lay EGGS, squawk\p"
	.string "at sunrise, and fight over feed\n"
	.string "like it’s a battle for the GYM.$"

ViridianLake_EventScript_FarmerDaughter::
	msgbox ViridianLake_Text_FarmerDaughter, MSGBOX_NPC
	end

ViridianLake_Text_FarmerDaughter:
	.string "Papa says not to name the SPEAROW,\n"
	.string "but I call the round one PECKY.\p"
	.string "She lays the shiniest eggs and\n"
	.string "only bites a little!$"

ViridianLake_EventScript_FarmerSon::
	msgbox ViridianLake_Text_FarmerSon, MSGBOX_NPC
	end

ViridianLake_Text_FarmerSon:
	.string "While Dad’s out wrangling SPEAROW,\n"
	.string "I’m raising a level 89 SWELLOW\l"
	.string "in SKY BRAWL IV.\p"
	.string "Way cooler, and it doesn’t poop on\n"
	.string "my boots.$"

ViridianLake_EventScript_FatMan::
	msgbox ViridianLake_Text_FatMan, MSGBOX_NPC
	end

ViridianLake_Text_FatMan:
	.string "I don’t swim much, but I like\n"
	.string "watchin’ the LAKE.\l"
	.string "Peaceful, y’know?$"

ViridianLake_EventScript_SoakedGuy::
	msgbox ViridianLake_Text_SoakedGuy, MSGBOX_NPC
	end

ViridianLake_Text_SoakedGuy:
	.string "I only went in a little,\n"
	.string "but my socks got soaked!\p"
	.string "Mom's gonna think a MAGIKARP\n"
	.string "did it!$"

ViridianLake_EventScript_GirlwithFriend::
	msgbox ViridianLake_Text_GirlwithFriend, MSGBOX_NPC
	end

ViridianLake_Text_GirlwithFriend:
	.string "We were playing by the water and then\n"
	.string "he said my POKéMON are weak...\p"
	.string "but I didn’t mean to cry!\n"
	.string "I just wanted to play!$"

ViridianLake_EventScript_BoywithFriend::
	msgbox ViridianLake_Text_BoywithFriend, MSGBOX_NPC
	end

ViridianLake_Text_BoywithFriend:
	.string "I didn’t mean to hurt her feelings...\n"
	.string "I just got mad 'cause she beat me\l"
	.string "again.\p"
	.string "Her POKéMON are not weak, they’re\n"
	.string "just better than mine.$"

ViridianLake_EventScript_Lass::
	msgbox ViridianLake_Text_Lass, MSGBOX_NPC
	end

ViridianLake_Text_Lass:
	.string "The sun’s just right, the breeze\n"
	.string "is perfect! this is the kind of day\l"
	.string "you have to spend near the water!$"

ViridianLake_EventScript_Mother::
	msgbox ViridianLake_Text_Mother, MSGBOX_NPC
	end

ViridianLake_Text_Mother:
	.string "Oh, don’t mind the noise, they’ve\n"
	.string "been pretending they’re POKéMON\l"
	.string "RANGERS all morning.\p"
	.string "If you’re lookin’ for peace and\n"
	.string "quiet, the LAKE’s your best bet!$"

ViridianLake_EventScript_Child1::
	msgbox ViridianLake_Text_Child1, MSGBOX_NPC
	end

ViridianLake_Text_Child1:
	.string "I’m on patrol!\n"
	.string "If any wild POKéMON get too close\l"
	.string "to town, I’ll calm ’em down,\p"
	.string "just like the real RANGERS do!$"

ViridianLake_EventScript_Child2::
	msgbox ViridianLake_Text_Child2, MSGBOX_NPC
	end

ViridianLake_Text_Child2:
	.string "They say a girl once fell into\n"
	.string "the LAKE and never came out...\p"
	.string "but some nights, when it’s really\n"
	.string "quiet, you can hear her humming\l"
	.string "from under the water.$"