ViridianLakeHydroelectricPlant_MapScripts::
	.byte 0

ViridianLakeHydroelectricPlant_EventScript_Worker1::
	msgbox ViridianLakeHydroelectricPlant_Text_Worker1, MSGBOX_NPC
	end

ViridianLakeHydroelectricPlant_Text_Worker1:
	.string "We keep the turbines running smooth,\n"
	.string "clean power from the LAKE, no coal,\l"
	.string "no smoke.\p"
	.string "Just don’t toss any LEFTOVERS in the\n"
	.string "intake valve, alright?$"

ViridianLakeHydroelectricPlant_EventScript_Worker2::
	msgbox ViridianLakeHydroelectricPlant_Text_Worker2, MSGBOX_NPC
	end

ViridianLakeHydroelectricPlant_Text_Worker2:
	.string "When the pressure spikes, we call\n"
	.string "in POLIWRATH!\p"
	.string "strong as a current and twice as\n"
	.string "stubborn.\p"
	.string "This plant wouldn’t run half as\n"
	.string "smooth without him!$"

ViridianLakeHydroelectricPlant_EventScript_Worker3::
	msgbox ViridianLakeHydroelectricPlant_Text_Worker3, MSGBOX_NPC
	end

ViridianLakeHydroelectricPlant_Text_Worker3:
	.string "The LAKE's steady flow keeps the\n"
	.string "turbines happy.\l"
	.string "It's quiet work most days...\p"
	.string "unless the local kids start tossing\n"
	.string "stones near the intake gate again!$"