ViridianLakeHydroelectricPlant_MapScripts::
	.byte 0

ViridianLakeHydroelectricPlant_EventScript_Worker1::
	msgbox ViridianLakeHydroelectricPlant_Text_Worker1, MSGBOX_NPC
	end

ViridianLakeHydroelectricPlant_Text_Worker1:
	.string "We keep the turbines running smooth,\n"
	.string "clean power from the LAKE, no coal,\l"
	.string "no smoke.\p"
	.string "Just don’t toss any LEFTOVERS in the\n"
	.string "intake valve, alright?$"

ViridianLakeHydroelectricPlant_EventScript_Worker2::
	msgbox ViridianLakeHydroelectricPlant_Text_Worker2, MSGBOX_NPC
	end

ViridianLakeHydroelectricPlant_Text_Worker2:
	.string "When the pressure spikes, we call\n"
	.string "in POLIWRATH!\p"
	.string "strong as a current and twice as\n"
	.string "stubborn.\p"
	.string "This plant wouldn’t run half as\n"
	.string "smooth without him!$"

ViridianLakeHydroelectricPlant_EventScript_Worker3::
	msgbox ViridianLakeHydroelectricPlant_Text_Worker3, MSGBOX_NPC
	end

ViridianLakeHydroelectricPlant_Text_Worker3:
	.string "The LAKE's steady flow keeps the\n"
	.string "turbines happy.\l"
	.string "It's quiet work most days...\p"
	.string "unless the local kids start tossing\n"
	.string "stones near the intake gate again!$"

ViridianLakeHydroelectricPlant_EventScript_Worker4::
	msgbox ViridianLakeHydroelectricPlant_Text_Worker4, MSGBOX_NPC
	end

ViridianLakeHydroelectricPlant_Text_Worker4:
	.string "We get the occasional HIKERS or\n"
	.string "tourists wandering too close,\p"
	.string "last week a curious PSYDUCK\n"
	.string "nearly tripped the alarm system.\p"
	.string "Cute, but not exactly OSHA\n"
	.string "compliant.$"

ViridianLakeHydroelectricPlant_EventScript_Worker5::
	msgbox ViridianLakeHydroelectricPlant_Text_Worker5, MSGBOX_NPC
	end

ViridianLakeHydroelectricPlant_Text_Worker5:
	.string "We keep a close eye on the\n"
	.string "water levels and foot traffic,\p"
	.string "trainers love the view, but one\n"
	.string "wrong step near the turbines,\p"
	.string "and it's not a sightseeing tour\n"
	.string "anymore.$"

ViridianLakeHydroelectricPlant_EventScript_Worker6::
	msgbox ViridianLakeHydroelectricPlant_Text_Worker6, MSGBOX_NPC
	end

ViridianLakeHydroelectricPlant_Text_Worker6:
	.string "We’ve had a few young trainees\n"
	.string "join as trainees lately...\p"
	.string "They often say that they’re more\n"
	.string "interested in volts than victories.\l"
	.string "The future’s in good hands.$"

ViridianLakeHydroelectricPlant_EventScript_Chief::
	msgbox ViridianLakeHydroelectricPlant_Text_Chief, MSGBOX_NPC
	end

ViridianLakeHydroelectricPlant_Text_Chief:
	.string "Every spark in KANTO starts here.\n"
	.string "My crew knows the weight of that,\p"
	.string "and we carry it like current\n"
	.string "through copper.$"

ViridianLakeHydroelectricPlant_EventScript_Child::
	msgbox ViridianLakeHydroelectricPlant_Text_Child, MSGBOX_NPC
	end

ViridianLakeHydroelectricPlant_Text_Child:
	.string "My friends told me that the old\n"
	.string "POWER PLANT was abandoned because\l"
	.string "a big monster that feeds on\p"
	.string "ELECTRICITY made its nest inside\n"
	.string "and no one has ever managed to\l"
	.string "chase it away!\p"
	.string "But when I tell adults about it,\n"
	.string "they just make fun of me...$"

ViridianLakeHydroelectricPlant_EventScript_Scientist1::
	msgbox ViridianLakeHydroelectricPlant_Text_Scientist1, MSGBOX_NPC
	end

ViridianLakeHydroelectricPlant_Text_Scientist1:
	.string "People forget this PLANT powers\n"
	.string "half the REGION.\p"
	.string "We used to have the POWER PLANT,\n"
	.string "but it was abandoned as it became\l"
	.string "obsolete.$"

ViridianLakeHydroelectricPlant_EventScript_Scientist2::
	msgbox ViridianLakeHydroelectricPlant_Text_Scientist2, MSGBOX_NPC
	end

ViridianLakeHydroelectricPlant_Text_Scientist2:
	.string "The LAKE’s energy output is stable,\n"
	.string "but lately...\p"
	.string "there’ve been fluctuations we can’t\n"
	.string "quite explain.\l"
	.string "Natural, maybe.\p"
	.string "Or not.$"